                                                __python implementation__

In [54]:
!pip install preprocess1

Requirement already satisfied: preprocess1 in c:\users\92241\anaconda3\lib\site-packages (0.1.42)
Requirement already satisfied: scikit-learn in c:\users\92241\anaconda3\lib\site-packages (from preprocess1) (1.7.2)
Requirement already satisfied: datetime in c:\users\92241\anaconda3\lib\site-packages (from preprocess1) (6.0)
Requirement already satisfied: pandas in c:\users\92241\anaconda3\lib\site-packages (from preprocess1) (2.3.3)
Requirement already satisfied: numpy in c:\users\92241\anaconda3\lib\site-packages (from preprocess1) (2.3.5)
Requirement already satisfied: ipywidgets in c:\users\92241\anaconda3\lib\site-packages (from preprocess1) (8.1.7)
Requirement already satisfied: IPython in c:\users\92241\anaconda3\lib\site-packages (from preprocess1) (9.16.1)
Requirement already satisfied: scipy in c:\users\92241\anaconda3\lib\site-packages (from preprocess1) (1.16.3)
Requirement already satisfied: datefinder in c:\users\92241\anaconda3\lib\site-packages (from preprocess1) (1.0.0)
Requirement already satisfied: pyod in c:\users\92241\anaconda3\lib\site-packages (from preprocess1) (3.6.5)
Requirement already satisfied: lightgbm in c:\users\92241\anaconda3\lib\site-packages (from preprocess1) (4.7.0)
Requirement already satisfied: regex>=2017.2.8 in c:\users\92241\anaconda3\lib\site-packages (from datefinder->preprocess1) (2025.9.1)
Requirement already satisfied: python-dateutil>=2.4.2 in c:\users\92241\anaconda3\lib\site-packages (from datefinder->preprocess1) (2.9.0.post0)
Requirement already satisfied: pytz in c:\users\92241\anaconda3\lib\site-packages (from datefinder->preprocess1) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\92241\anaconda3\lib\site-packages (from python-dateutil>=2.4.2->datefinder->preprocess1) (1.17.0)
Requirement already satisfied: zope.interface in c:\users\92241\anaconda3\lib\site-packages (from datetime->preprocess1) (8.0.1)
Requirement already satisfied: colorama>=0.4.4 in c:\users\92241\anaconda3\lib\site-packages (from IPython->preprocess1) (0.4.6)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\92241\anaconda3\lib\site-packages (from IPython->preprocess1) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in c:\users\92241\anaconda3\lib\site-packages (from IPython->preprocess1) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.6 in c:\users\92241\anaconda3\lib\site-packages (from IPython->preprocess1) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\92241\anaconda3\lib\site-packages (from IPython->preprocess1) (3.0.52)
Requirement already satisfied: psutil>=7 in c:\users\92241\anaconda3\lib\site-packages (from IPython->preprocess1) (7.0.0)
Requirement already satisfied: pygments>=2.14.0 in c:\users\92241\anaconda3\lib\site-packages (from IPython->preprocess1) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\92241\anaconda3\lib\site-packages (from IPython->preprocess1) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\92241\anaconda3\lib\site-packages (from IPython->preprocess1) (5.14.3)
Requirement already satisfied: wcwidth in c:\users\92241\anaconda3\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->IPython->preprocess1) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\92241\anaconda3\lib\site-packages (from jedi>=0.18.2->IPython->preprocess1) (0.8.5)
Requirement already satisfied: executing>=1.2.0 in c:\users\92241\anaconda3\lib\site-packages (from stack_data>=0.6.0->IPython->preprocess1) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\92241\anaconda3\lib\site-packages (from stack_data>=0.6.0->IPython->preprocess1) (3.0.0)
Requirement already satisfied: pure_eval in c:\users\92241\anaconda3\lib\site-packages (from stack_data>=0.6.0->IPython->preprocess1) (0.2.3)
Requirement already satisfied: comm>=0.1.3 in c:\users\92241\anaconda3\lib\site-packages (from ipywidgets->preprocess1) (0.2.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\users\92241\anaconda3\lib\site-packages (from ipywidgets->preprocess1) (4.0.14)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\users\92241\anaconda3\lib\site-packages (from ipywidgets->preprocess1) (3.0.15)
Requirement already satisfied: narwhals>=1.15 in c:\users\92241\anaconda3\lib\site-packages (from lightgbm->preprocess1) (2.7.0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\92241\anaconda3\lib\site-packages (from pandas->preprocess1) (2025.2)
Requirement already satisfied: joblib>=1.5 in c:\users\92241\anaconda3\lib\site-packages (from pyod->preprocess1) (1.5.2)
Requirement already satisfied: matplotlib in c:\users\92241\anaconda3\lib\site-packages (from pyod->preprocess1) (3.10.0)
Requirement already satisfied: numba>=0.51 in c:\users\92241\anaconda3\lib\site-packages (from pyod->preprocess1) (0.62.1)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in c:\users\92241\anaconda3\lib\site-packages (from numba>=0.51->pyod->preprocess1) (0.45.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\92241\anaconda3\lib\site-packages (from scikit-learn->preprocess1) (3.5.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\92241\anaconda3\lib\site-packages (from matplotlib->pyod->preprocess1) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\92241\anaconda3\lib\site-packages (from matplotlib->pyod->preprocess1) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\92241\anaconda3\lib\site-packages (from matplotlib->pyod->preprocess1) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\92241\anaconda3\lib\site-packages (from matplotlib->pyod->preprocess1) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\92241\anaconda3\lib\site-packages (from matplotlib->pyod->preprocess1) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\92241\anaconda3\lib\site-packages (from matplotlib->pyod->preprocess1) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\92241\anaconda3\lib\site-packages (from matplotlib->pyod->preprocess1) (3.2.5)

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\92241\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\92241\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\92241\anaconda3\Lib\site-packages)

In [55]:
import pickle   # importing pickle for saving and loading machine learning models
import pandas as pd  # importing pandas for analyzing, cleaning, exploring, and manipulating data
from sklearn.model_selection import train_test_split  # importing train_test_split for spliting the data
from preprocess1 import *  # importing * for import all functions at once
from imblearn.over_sampling import SMOTE  # importing SMOTE for Balancing the Data

In [56]:
df=pd.read_csv("C:/Users/92241/Desktop/Study Space/AI/5. Machine Learning Expert/1. Content Material/2. SVM/loan_approved.csv")
df# Loading dataset

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved)
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [57]:
df.columns
df# Checking coloums of datasets

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved)
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [58]:
df.isnull().sum()  # Checking null values

Loan_ID                    0
Gender                    13
Married                    3
Dependents                15
Education                  0
Self_Employed             32
ApplicantIncome            0
CoapplicantIncome          0
LoanAmount                22
Loan_Amount_Term          14
Credit_History            50
Property_Area              0
Loan_Status (Approved)     0
dtype: int64

# Imputing Null values

In [59]:
df.loc[df['Gender'].isnull(),'Gender']="Male"  # Filling null value using Most_Frequent Elements of Gender column.

In [60]:
df.loc[df['Married'].isnull(),'Married']="Yes"    # Filling null value using Most_Frequent Elements of Married column.

In [61]:
df.loc[df['Dependents'].isnull(),'Dependents']='0'   # Filling null value using Most_Frequent Elements of Dependents

In [96]:
df.loc[df['Self_Employed'].isnull(),'Self_Employed']='No'
df# Filling null value using Most_Frequent Elements of Self_Employed

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved)
0,LP001002,Male,No,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [63]:
#  Filling null values using Median of LoanAmount
df.loc[df['LoanAmount'].isnull(),'LoanAmount']=df['LoanAmount'].median()

In [64]:
#  Filling null values using Most_Frequent value of Loan_Amount_Term column
df.loc[df['Loan_Amount_Term'].isnull(),'Loan_Amount_Term']=360.0

In [65]:
df.loc[df['Credit_History'].isnull(),'Credit_History']=0.0    # Filling null values of Credit_History

In [66]:
df.isnull().sum()   # Checking null values are available or not

Loan_ID                   0
Gender                    0
Married                   0
Dependents                0
Education                 0
Self_Employed             0
ApplicantIncome           0
CoapplicantIncome         0
LoanAmount                0
Loan_Amount_Term          0
Credit_History            0
Property_Area             0
Loan_Status (Approved)    0
dtype: int64

# Loading preprocessor

In [97]:
import pickle   # importing pickle for saving and loading machine learning models
from sklearn.preprocessing import LabelEncoder

class ModifiedLabelEncoder(LabelEncoder):
    # Override fit_transform to accept an optional 'y' argument
    # and pass only 'X' to the parent LabelEncoder's fit_transform
    def fit_transform(self, X, y=None):
        # Reshape the output to be 2D
        return super().fit_transform(X).reshape(-1, 1)

    # Also override transform for consistency, though it might not be strictly necessary for this error
    def transform(self, X, y=None):
        # Reshape the output to be 2D
        return super().transform(X).reshape(-1, 1)

def divide_by_12(x):
    # Custom function to divide a value by 12, likely for 'Loan_Amount_Term'
    return x / 12

def same(x):
    # Custom function that acts as a pass-through, returning the input unchanged
    return x

with open(
    "preprocessor1.pkl",
    "rb"
) as f:
    preprocessor = pickle.load(f)

In [98]:
preprocessor  # Preprocessor or PipeLine

ColumnTransformer(transformers=[('OHE columns', OneHotEncoder(),
                                 ['Self_Employed', 'Property_Area', 'Gender']),
                                ('Label_encoder', ModifiedLabelEncoder(),
                                 'Married'),
                                ('standard_scaler', StandardScaler(),
                                 ['ApplicantIncome', 'CoapplicantIncome',
                                  'LoanAmount']),
                                ('custom',
                                 FunctionTransformer(func=<function divide_by_12 at 0x0000015BAC43BEC0>),
                                 ['Loan_Amount_Term']),
                                ('pass through',
                                 FunctionTransformer(func=<function same at 0x0000015BABFE3060>),
                                 ['Credit_History']),
                                ('ordinal dependents',
                                 OrdinalEncoder(categories=[['0', '1', '2',
                                                             '3+']]),
                                 ['Dependents']),
                                ('ordinal education',
                                 OrdinalEncoder(categories=[['Not Graduate',
                                                             'Graduate']]),
                                 ['Education']),
                                ('Label Label encoder', ModifiedLabelEncoder(),
                                 ['Loan_Status (Approved)'])])

# Splitting the data

In [99]:
# Spliting the data into train and test
x_train,x_test,y_train,y_test=train_test_split(df,df['LoanAmount'],test_size=0.2)

In [102]:
x_train['Loan_Status (Approved)'].value_counts()  # Checking count of unique values of Loan_Status (Approved) columns

Loan_Status (Approved)
Y    339
N    152
Name: count, dtype: int64

# Transforming the data

In [103]:
# Transform the training data using the preprocessor object or PipeLine
processed_data=preprocessor.fit_transform(x_train)

In [104]:
processed_data

array([[1., 0., 0., ..., 0., 1., 1.],
       [1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.],
       ...,
       [1., 0., 0., ..., 0., 1., 1.],
       [1., 0., 1., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 1.]], shape=(491, 16))

In [105]:
# Extract the features (all columns except the last one) from the processed data
x_train1=processed_data[:,:-1]

In [106]:
# Extract the target variable (last column) from the processed data
y_train1=processed_data[:,-1] # Last column is target

In [107]:
y_train1

array([1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0.,
       1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1.,
       1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0.,
       1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1.,
       1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1.])

# Balancing the data

## SMOTE

In [108]:
#!pip install imblearn

In [109]:
# Initialize the SMOTE (Synthetic Minority Over-sampling Technique) object into variable
smote=SMOTE()

In [110]:
# Apply SMOTE to the training data to balance the class distribution
x_train_smote,y_train_smote=smote.fit_resample(x_train1,y_train1)

In [111]:
len(y_train)  # Checking length of actual y_train

491

In [112]:
len(y_train_smote)   # Checking length of y_train after apply Smote

678

# Model Building

SVM is the Supervised Machine Learning algorithm used for both classification, regression. But mostly preferred for classification.

Given a dataset, the algorithm tries to divide the data using hyperplanes and then makes the predictions. SVM is a non-probabilistic linear classifier. While other classifiers, when classifying, predict the probability of a data point to belong to one group or the another, SVM directly says to which group the datapoint belongs to without using any probability calculation.

How it works?

SVM constructs a best line or the decision boundary called Hyperplane which can be used for classification or regression or outlier detection. The dimension of the hyperplane depends upon the number of features. If the number of input features is 2, then the hyperplane is just a line. If the number of input features is 3, then the hyperplane becomes a two-dimensional plane.

This hyperplane creates 2 margin lines parallel to it which have some distance so that it can distinctly classify the data points. The distance between the 2 margin lines are called marginal distance.

These 2 margin lines passes through the most nearest +ve points and the most nearest -ve points. Those points through which the margin lines pass are called support vectors. Support vectors are important as it helps to determine the maximum distance of the marginal plane.

## Understanding the Mathematics involved

Let’s take the example of the following dataset and see how can we divide the data into appropriate groups.

We can see that there are two groups of data. The question is how to divide these points into two groups. It can be done using any of the three lines. Or, for that purpose, there can be an infinite number of straight lines that can divide these points into two classes. Now, which line to choose? SVM solves this problem using the maximum margin as shown

The black line in the middle is the optimum classifier. This line is drawn to maximise the distance of the classifier line from the nearest points in the two classes. It is also called a hyperplane in terms of SVM. A Hyperplane is an n-1 dimensional plane which optimally divides the data of n dimensions. Here, as we have only a 2-D data, so the hyperplane can be represented using one dimension only. Hence, the hyperplane is a line here. The two points (highlighted with circles) which are on the yellow lines, they are called the support vectors. As it is a 2-D figure, they are points. In a multi-dimensional space, they will be vectors, and hence, the name- support vector machine as the algorithm creates the optimum classification line by maximising its distance from the two support vectors.

When the data is not linearly separable, then to create a hyperplane to separate data into different groups, the SVM algorithm needs to perform computations in a higher-dimensional space. But the introduction of new dimensions makes the computations for the SVMs more intensive, which impacts the algorithm performance. To rectify this, mathematicians came up with the approach of Kernel methods. Kernel methods use kernel functions available in mathematics. The unique feature of a kernel function is to compute in a higher-dimensional space without calculating the new coordinates in that higher dimension. It implicitly uses predefined mathematical functions to do operations on the existing points which mimic the computation in a higher-dimensional space without adding to the computation cost as they are not actually calculating the coordinates in the higher dimension thereby avoiding the computation of calculating distances from the newly computed points. This is called the kernel trick.  Image: bogotobogo.com

In the left diagram above, we have a non-linear distribution of data as we can not classify a data using a linear equation. To solve this problem, we can project the points in a 3-dimensional space and then derive a plane which divides the data into two parts. In theory, that’s what a kernel function does without computing the additional coordinates for the higher dimension.

In [113]:
from sklearn.svm import SVC  # # assign Support vector classifier
svclassifier = SVC() ## base model with default parameters
svclassifier.fit(x_train_smote,y_train_smote)  ## Fit the SVC to the resampled training data

SVC()

# Validating the model

### Proessing the test data

In [119]:
x_test_processed=preprocessor.transform(x_test)  # Transform the test data using the preprocessor

In [125]:
x_test=x_test_processed[:,:-1]  # Extract the features (all columns except the last one) from the processed data
y_test=x_test_processed[:,-1]   # Extract the target variable (last column) from the processed data

In [126]:
y_test

array([1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0.,
       1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1.,
       1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0.,
       1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1.,
       0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1.,
       1., 0., 0., 1.])

In [127]:
# Getting predictions from model
y_pred=svclassifier.predict(x_test)

### Evaluating the model performance

In [128]:
# Importing the classification_report function from sklearn.metrics
from sklearn.metrics import classification_report
# Printing the classification report comparing the true labels (y_test) and the predicted labels (y_pred)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.50      0.07      0.13        40
         1.0       0.68      0.96      0.80        83

    accuracy                           0.67       123
   macro avg       0.59      0.52      0.47       123
weighted avg       0.62      0.67      0.58       123

# Hyper Parameter Tuning

## What is a Model Hyperparameter?

A model hyperparameter is a configuration that is external to the model and whose value cannot be estimated from data.

## Hyperparameters of Support Vector Machine

#### SVM separates data points that belong to different classes with a decision boundary. When determining the decision boundary, a soft margin SVM (soft margin means allowing some data points to be misclassified) tries to solve an optimization problem with the following goals:

#### 1)Increase the distance of decision boundary to classes (or support vectors)
#### 2)Maximize the number of points that are correctly classified in the training set

### There is obviously a trade-off between these two goals which and it is controlled by C which adds a penalty for each misclassified data point.

### If C is small, the penalty for misclassified points is low so a decision boundary with a large margin is chosen at the expense of a greater number of misclassification.

### If C is large, SVM tries to minimize the number of misclassified examples due to the high penalty which results in a decision boundary with a smaller margin. The penalty is not the same for all misclassified examples. It is directly proportional to the distance to the decision boundary.

### Gamma is a hyperparameter used with non-linear SVM. One of the most commonly used non-linear kernels is the radial basis function (RBF). Gamma parameter of RBF controls the distance of the influence of a single training point.

### Low values of gamma indicate a large similarity radius which results in more points being grouped together.

### For high values of gamma, the points need to be very close to each other in order to be considered in the same group (or class). Therefore, models with very large gamma values tend to overfit.

## GridSearchCV

#### It is the process of performing hyperparameter tuning in order to determine the optimal values for a given model. As mentioned above, the performance of a model significantly depends on the value of hyperparameters

#### Doing this manually could take a considerable amount of time and resources and thus we use GridSearchCV to automate the tuning of hyperparameters.

GridSearchCV tries all the combinations of the values passed in the m

dictionary and evaluates the model for each combination using the Cross-Validation method. Hence after using this function we get accuracy/loss for every combination of hyperparameters and we can choose the one with the best performance.

- gamma = 'auto' ![image.png](attachment:924fc53c-a5eb-4078-ab44-4a713bb08a45.png)
- gamma = 'scale' ![image.png](attachment:45dd628f-ae44-4b59-a610-311f3e18b7b6.png)

In [132]:
from itertools import product  # Importing the product function from itertools module

param_grid_linear = {           #  Define Parameter grid for linear kernel SVM
    'C': [0.1, 5, 10,50,60,70],
    'kernel': ['linear'],
    'gamma': ['scale', 'auto']
}
param_grid_rbf = {              # Define Parameter grid for Radial Basic Function-RBF
    'C': [0.1, 5, 10,50,60,70],
    'kernel': ['rbf'],
    'gamma': ['scale', 'auto']
}
param_grid_poly = {             # Define Parameters grid for Polynomial kernel
    'C': [0.1, 5, 10,50,60,70],
    'kernel': ['poly'],
    'gamma': ['scale', 'auto'],
    'degree': [2, 3, 4]
}

In [140]:
#gamma ↓
#influence range ↑
#boundary smoother


#gamma ↑
#influence range ↓
#boundary more complex



#gamma='auto'
#→ γ = 1 / number of features

#gamma='scale'
#→ γ = 1 / (number of features × variance)

In [133]:
# Importing GridSearchCV from sklearn
from sklearn.model_selection import GridSearchCV

# Assigning SVC model into variables
model=SVC()

# Defining the grid search using GridSearchCV
# - The parameter grid is defined by param_grid_poly
# - 'refit=True' ensures that the best estimator found during the grid search is refitted on the whole dataset
# - 'verbose=2' controls the verbosity of the grid search process (higher values result in more output)
# - 'scoring='f1'' specifies the scoring metric for evaluating the model's performance during grid search
# - 'cv=5' specifies 5-fold cross-validation for evaluating each combination of hyperparameters
grid = GridSearchCV(model,param_grid=param_grid_rbf, refit = True, verbose = 1,scoring='f1',cv=3)

# fitting the model for grid search
grid.fit(x_train_smote,y_train_smote)

Fitting 3 folds for each of 12 candidates, totalling 36 fits

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [0.1, 5, 10, 50, 60, 70],
                         'gamma': ['scale', 'auto'], 'kernel': ['rbf']},
             scoring='f1', verbose=1)

In [134]:
# Opening a file named "model.pkl" in write-binary mode
# The 'wb' mode is used for writing binary data to the file
with open("model.pkl","wb") as f:
    pickle.dump(grid,f)      # Using pickle to serialize and save the grid search object to the file

In [135]:
print(grid.best_params_)   # Printing the best parameters found by the grid search

{'C': 5, 'gamma': 'auto', 'kernel': 'rbf'}

In [136]:
grid

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [0.1, 5, 10, 50, 60, 70],
                         'gamma': ['scale', 'auto'], 'kernel': ['rbf']},
             scoring='f1', verbose=1)

In [137]:

svclassifier = SVC(C=10, gamma='auto',kernel='rbf' ) ## base model with default parameters
svclassifier.fit(x_train_smote,y_train_smote)

SVC(C=10, gamma='auto')

In [138]:
y_hat=grid.predict(x_test)  # Use the best model from grid search to make predictions on the test set

In [139]:
# Generate a classification report comparing true labels (y_test) with predicted labels (y_hat)
print(classification_report(y_test,y_hat))

              precision    recall  f1-score   support

         0.0       0.66      0.68      0.67        40
         1.0       0.84      0.83      0.84        83

    accuracy                           0.78       123
   macro avg       0.75      0.75      0.75       123
weighted avg       0.78      0.78      0.78       123